elasticsearch:
  host: "http://192.168.0.250:19200"
  indices:
    doc_index: "chs_guide_docs"
    image_index: "portal_image_vector"
    data_index: "chs19_all_labeled"

llm:
  api_key: "none"
  base_url: "http://192.168.0.240:12507/v1"
  model_name: "RedHatAI/gemma-3-27b-it-FP8-dynamic"
  temperature: 0.1
  max_token: 2048

embedding:
  api_key: "none"
  base_url: "http://192.168.0.240:12508/v1"
  text_model: "dragonkue/BGE-m3-ko"
  image_model: "dragonkue/BGE-m3-ko"